import { PUBLIC_API_BASE_URL } from "./base-url.js";
import { AGENT_READINESS_BILLING_UNIT, getAgentReadinessPriceUsdc } from "./agent-readiness/product-pricing.js";

export function capabilityManifest() {
  const readinessPrice = getAgentReadinessPriceUsdc();
  return {
    manifest_type: "santos-capability-manifest",
    manifest_version: "1.0.0",
    standard: false,
    name: "Santos Website Intelligence API",
    description: "An AI Website Intelligence API that measures whether websites can be discovered, understood, trusted, and used by AI agents. This vendor-specific discovery metadata is not an IETF, MCP, or Schema.org standard.",
    version: "2.3.1",
    provider: { name: "Santos Automation", url: "https://www.santosautomation.com" },
    documentation_url: `${PUBLIC_API_BASE_URL}/openapi.json`,
    openapi_url: `${PUBLIC_API_BASE_URL}/openapi.json`,
    mcp_url: `${PUBLIC_API_BASE_URL}/mcp`,
    authentication: "No account or traditional API key. Paid resources use x402 v2; deep report reads use a per-job bearer token.",
    payment_protocols: [{ protocol: "x402-v2", network: "eip155:8453", currency: "USDC" }],
    human_purchase: {
      product: "Agent Readiness Report",
      price: { amount: "5.00", currency: "USD", rail: "stripe-card" },
      url: "https://www.santosautomation.com/agent-readiness/buy",
      note: "Human convenience: one-time card purchase, emailed as a private tokened link, no account. The machine-payable per-call price remains $0.075 USDC via x402.",
    },
    support_url: "mailto:info@santosautomation.com",
    terms_url: "https://www.santosautomation.com/terms",
    privacy_url: "https://www.santosautomation.com/terms#privacy",
    capabilities: [
      {
        id: "site-audit.quick", title: "Quick Intelligence Audit", version: "2.1.0", description: "Select for synchronous lightweight website intelligence triage of one public page.",
        endpoint: `${PUBLIC_API_BASE_URL}/api/audit?url={url}`, method: "GET", mode: "synchronous",
        expected_latency: "seconds", input_schema: { type: "object", required: ["url"], properties: { url: { type: "string", format: "uri" } } },
        output_schema: `${PUBLIC_API_BASE_URL}/openapi.json#/paths/~1api~1audit/get/responses/200`,
        access: "x402 v2 payment; no account or API key", billing_unit: "successful audit", idempotency: "safe GET; payment settles only on a successful response",
        side_effects: "read-only public fetch", rate_limits: "bounded target fetch", error_model: "stable JSON code and message", data_retention: "no target credentials or cookies collected",
        limitations: ["single page", "no JavaScript rendering", "not WCAG certification or a vulnerability scan"],
        documentation: `${PUBLIC_API_BASE_URL}/openapi.json`, support: "mailto:info@santosautomation.com",
        price: { amount: "0.015", currency: "USDC", protocol: "x402-v2", network: "eip155:8453" },
      },
      {
        id: "agent-readiness.quick", title: "Agent Readiness Audit", version: "1.0.0", description: "Select to assess public agent-facing discovery, APIs, MCP, trust, and resource-scoped machine-commerce pricing without active target actions.",
        endpoint: `${PUBLIC_API_BASE_URL}/api/agent-readiness?url={url}`, method: "GET", mode: "synchronous",
        expected_latency: "seconds", input_schema: { type: "object", required: ["url"], properties: { url: { type: "string", format: "uri" }, depth: { type: "string", enum: ["quick"] } } },
        output_schema: `${PUBLIC_API_BASE_URL}/openapi.json#/components/schemas/AgentReadinessResult`,
        access: "x402 v2 payment; no account or API key", billing_unit: AGENT_READINESS_BILLING_UNIT,
        idempotency: "safe read-only GET; payment settles only on a successful response", side_effects: "none on the target beyond bounded public reads", rate_limits: "maximum eight additional public requests",
        error_model: "stable JSON code and message", data_retention: "no authentication, payment signature, cookie, or secret collection",
        limitations: ["public surfaces only", "does not authenticate to or pay the audited target", "no MCP tools/call", "llms.txt proposal and optional preview-registry evidence"],
        documentation: `${PUBLIC_API_BASE_URL}/openapi.json`, support: "mailto:info@santosautomation.com",
        schema_version: "1.0.0", price: { amount: readinessPrice, currency: "USDC", protocol: "x402-v2", network: "eip155:8453" },
      },
      {
        id: "web.safe-fetch", title: "Safe Fetch", version: "1.0.0", description: "Select to retrieve one public URL's raw text body through a hardened SSRF-guarded fetcher with redirects, headers, and timing metadata.",
        endpoint: `${PUBLIC_API_BASE_URL}/v1/fetch?url={url}`, method: "GET", mode: "synchronous",
        expected_latency: "seconds", input_schema: { type: "object", required: ["url"], properties: { url: { type: "string", format: "uri" } } },
        output_schema: `${PUBLIC_API_BASE_URL}/openapi.json#/paths/~1v1~1fetch/get/responses/200`,
        access: "x402 v2 payment; no account or API key", billing_unit: "successful fetch", idempotency: "read-only; payment settles only on a successful response",
        side_effects: "read-only public fetch", rate_limits: "bounded target fetch (15s, 5MB, ports 80/443)", error_model: "stable JSON code and message", data_retention: "fetched content is returned, not stored",
        limitations: ["single URL", "text formats only", "no crawling", "no JavaScript rendering"],
        documentation: `${PUBLIC_API_BASE_URL}/openapi.json`, support: "mailto:info@santosautomation.com",
        price: { amount: process.env.SAFE_FETCH_PRICE_USDC ?? "0.002", currency: "USDC", protocol: "x402-v2", network: "eip155:8453" },
      },
      {
        id: "content.extract-markdown", title: "Page-to-Markdown Extraction", version: "1.0.0", description: "Select to convert one public web page into clean Markdown with title, links, and metadata for RAG and research workflows.",
        endpoint: `${PUBLIC_API_BASE_URL}/v1/extract`, method: "POST", mode: "synchronous",
        expected_latency: "seconds", input_schema: { type: "object", required: ["url"], properties: { url: { type: "string", format: "uri" } } },
        output_schema: `${PUBLIC_API_BASE_URL}/openapi.json#/paths/~1v1~1extract/post/responses/200`,
        access: "x402 v2 payment; no account or API key", billing_unit: "successful extraction", idempotency: "read-only; payment settles only on a successful response",
        side_effects: "read-only public fetch", rate_limits: "bounded target fetch (15s, 5MB)", error_model: "stable JSON code and message", data_retention: "page content is returned, not stored",
        limitations: ["single page", "no crawling", "no JavaScript rendering"],
        documentation: `${PUBLIC_API_BASE_URL}/openapi.json`, support: "mailto:info@santosautomation.com",
        price: { amount: process.env.EXTRACT_PRICE_USDC ?? "0.005", currency: "USDC", protocol: "x402-v2", network: "eip155:8453" },
      },
      {
        id: "render.screenshot", title: "Screenshot & PDF Render", version: "1.0.0", description: "Select to render one public page as a PNG, JPEG, or PDF in a real isolated Chromium browser.",
        endpoint: `${PUBLIC_API_BASE_URL}/v1/screenshot?url={url}`, method: "GET", mode: "synchronous",
        expected_latency: "seconds (a cold worker wakes on demand; retry on 504)", input_schema: { type: "object", required: ["url"], properties: { url: { type: "string", format: "uri" }, format: { type: "string", enum: ["png", "jpeg", "pdf"] }, device: { type: "string", enum: ["desktop", "mobile"] }, full_page: { type: "boolean" } } },
        output_schema: `${PUBLIC_API_BASE_URL}/openapi.json#/paths/~1v1~1screenshot/get/responses/200`,
        access: "x402 v2 payment; no account or API key", billing_unit: "successful render", idempotency: "read-only; payment settles only when render bytes are returned",
        side_effects: "read-only public browser navigation", rate_limits: "bounded browser requests, bytes, and runtime", error_model: "stable JSON code and message on failures; binary on success", data_retention: "render artifacts expire within 72 hours",
        limitations: ["single page", "no authenticated flows", "binary response"],
        documentation: `${PUBLIC_API_BASE_URL}/openapi.json`, support: "mailto:info@santosautomation.com",
        price: { amount: process.env.SCREENSHOT_PRICE_USDC ?? "0.01", currency: "USDC", protocol: "x402-v2", network: "eip155:8453" },
      },
      {
        id: "site-audit.deep-page", title: "Deep Website Intelligence Audit", version: "3.0.0", description: "Select for browser-rendered website intelligence evidence and optional Agent Readiness discovery.",
        endpoint: `${PUBLIC_API_BASE_URL}/v1/audits`, method: "POST", mode: "asynchronous",
        expected_latency: "tens of seconds to minutes", input_schema: `${PUBLIC_API_BASE_URL}/openapi.json#/paths/~1v1~1audits/post/requestBody`, output_schema: `${PUBLIC_API_BASE_URL}/openapi.json#/paths/~1v1~1audits~1{job_id}~1report/get/responses/200`,
        access: "x402 v2 payment plus per-job bearer access token", billing_unit: "bounded compute reservation", idempotency: "Idempotency-Key supported",
        side_effects: "read-only public browser navigation", rate_limits: "bounded browser requests, bytes, runtime, and artifacts", error_model: "versioned job and report errors",
        data_retention: "short-lived report artifacts; target cookie values are never captured", limitations: ["single page", "lab data", "no authenticated flows or penetration testing"],
        documentation: `${PUBLIC_API_BASE_URL}/openapi.json`, support: "mailto:info@santosautomation.com",
        price: { amount: process.env.DEEP_AUDIT_PRICE_USDC ?? "0.225", currency: "USDC", protocol: "x402-v2", network: "eip155:8453" },
      },
    ],
  };
}
