import { PUBLIC_API_BASE_URL } from "./base-url.js";
import { AGENT_READINESS_BILLING_UNIT, getAgentReadinessPriceUsdc } from "./agent-readiness/product-pricing.js";

export function capabilityManifest() {
  const readinessPrice = getAgentReadinessPriceUsdc();
  return {
    manifest_type: "santos-capability-manifest",
    manifest_version: "1.0.0",
    standard: false,
    name: "Santos Website Intelligence API",
    description: "An AI Website Intelligence API that measures whether websites can be discovered, understood, trusted, and used by AI agents. This vendor-specific discovery metadata is not an IETF, MCP, or Schema.org standard.",
    version: "2.9.0",
    provider: { name: "Santos Automation", url: "https://www.santosautomation.com" },
    documentation_url: `${PUBLIC_API_BASE_URL}/openapi.json`,
    openapi_url: `${PUBLIC_API_BASE_URL}/openapi.json`,
    mcp_url: `${PUBLIC_API_BASE_URL}/mcp`,
    authentication: "No account or traditional API key. Paid resources use x402 v2; deep report reads use a per-job bearer token.",
    payment_protocols: [{ protocol: "x402-v2", network: "eip155:8453", currency: "USDC" }],
    human_purchase: {
      product: "Agent Readiness Report",
      price: { amount: "5.00", currency: "USD", rail: "stripe-card" },
      url: "https://www.santosautomation.com/agent-readiness/buy",
      note: "Human convenience: one-time card purchase, emailed as a private tokened link, no account. The machine-payable per-call price remains $0.075 USDC via x402.",
    },
    support_url: "mailto:info@santosautomation.com",
    terms_url: "https://www.santosautomation.com/terms",
    privacy_url: "https://www.santosautomation.com/terms#privacy",

    // Canonical error contract. Every non-2xx JSON error body shares one
    // shape; `code` is stable and machine-actionable, `for_humans` appears on
    // responses a person is likely to hit in a browser.
    error_model: {
      shape: { error: "string — human-readable message", code: "string — stable machine code (see error_codes)", for_humans: "string, optional — plain-language next step", retry_after: "integer seconds, optional — present on 429" },
      paid_endpoints: "An unpaid request always receives 402 with a base64 PAYMENT-REQUIRED header (x402 v2 terms) before any validation error; payment settles only on a <400 response, so a failed call is never charged.",
      error_codes: [
        { code: "PAYMENT_REQUIRED", status: 402, meaning: "x402 terms attached in PAYMENT-REQUIRED; sign and retry with PAYMENT-SIGNATURE." },
        { code: "INVALID_URL", status: 400, meaning: "Target is not a parseable public http(s) URL (or a redirect target is not)." },
        { code: "UNSUPPORTED_SCHEME", status: 400, meaning: "Only http: and https: targets are accepted." },
        { code: "UNSUPPORTED_PORT", status: 400, meaning: "Destination port is outside the allowed set (80/443)." },
        { code: "UNSUPPORTED_CONTENT_TYPE", status: 400, meaning: "Target returned a content type the endpoint cannot process." },
        { code: "PRIVATE_ADDRESS_BLOCKED", status: 400, meaning: "Target is (or resolves to) a private, reserved, or loopback address — SSRF guard." },
        { code: "TARGET_UNREACHABLE", status: 502, meaning: "DNS resolution or TCP connection to the target failed." },
        { code: "FETCH_BUDGET_EXCEEDED", status: 502, meaning: "Agent Readiness bounded-request budget exhausted before the assessment completed." },
        { code: "RATE_LIMITED", status: 429, meaning: "Free-tier quota exhausted; retry_after tells you when it resets (UTC midnight)." },
        { code: "EMAIL_NOT_VERIFIED", status: 401, meaning: "Verified-email token missing or invalid; re-run the /api/leads/verify flow." },
        { code: "EMAIL_DELIVERY_FAILED", status: 503, meaning: "The verification email could not be sent; try again later." },
        { code: "INVALID_CODE", status: 400, meaning: "Verification code does not match the latest code issued for that email." },
        { code: "CODE_EXPIRED", status: 410, meaning: "Verification code is older than 10 minutes; request a fresh one." },
        { code: "INVALID_REQUEST", status: 400, meaning: "Malformed request body or parameters." },
        { code: "INVALID_JSON", status: 400, meaning: "Request body is not valid JSON." },
        { code: "BODY_TOO_LARGE", status: 413, meaning: "Request body exceeds the endpoint's byte cap." },
        { code: "UNAUTHORIZED", status: 401, meaning: "Missing or invalid per-job bearer token (deep audit report reads)." },
        { code: "SERVICE_UNAVAILABLE", status: 503, meaning: "A backing store or worker is not configured or unreachable; honest outage, retry later." },
      ],
    },

    capabilities: [
      {
        id: "site-audit.quick", title: "Quick Intelligence Audit", version: "2.1.0", description: "Select for synchronous lightweight website intelligence triage of one public page.",
        endpoint: `${PUBLIC_API_BASE_URL}/api/audit?url={url}`, method: "GET", mode: "synchronous",
        expected_latency: "seconds", input_schema: { type: "object", required: ["url"], properties: { url: { type: "string", format: "uri" } } },
        output_schema: `${PUBLIC_API_BASE_URL}/openapi.json#/paths/~1api~1audit/get/responses/200`,
        access: "x402 v2 payment; no account or API key", billing_unit: "successful audit", idempotency: "safe GET; payment settles only on a successful response",
        side_effects: "read-only public fetch", rate_limits: "bounded target fetch", error_model: "stable JSON code and message", data_retention: "no target credentials or cookies collected",
        limitations: ["single page", "no JavaScript rendering", "not WCAG certification or a vulnerability scan"],
        documentation: `${PUBLIC_API_BASE_URL}/openapi.json`, support: "mailto:info@santosautomation.com",
        price: { amount: "0.015", currency: "USDC", protocol: "x402-v2", network: "eip155:8453" },
        examples: {
          request: `curl "${PUBLIC_API_BASE_URL}/api/audit?url=https://example.com" -H "PAYMENT-SIGNATURE: <x402 v2 signed payload>"`,
          response: { tier: "paid", url: "https://example.com/", http_status: 200, overall_score: 68, website_intelligence_score: 74, scores: { performance: 100, seo: 40, accessibility: 100, security: 33 }, issues: ["Missing canonical link"], signature_alg: "HMAC-SHA256", signature: "<hex>" },
        },
      },
      {
        id: "site-audit.quick-batch", title: "Batch Quick Intelligence Audit", version: "1.0.0", description: "Select for volume triage: up to 50 public URLs audited for one flat payment, per-URL failure isolation.",
        endpoint: `${PUBLIC_API_BASE_URL}/api/audit/batch`, method: "POST", mode: "synchronous",
        expected_latency: "seconds to a few minutes", input_schema: { type: "object", required: ["urls"], properties: { urls: { type: "array", minItems: 1, maxItems: 50, items: { type: "string", format: "uri" } } } },
        output_schema: `${PUBLIC_API_BASE_URL}/openapi.json#/paths/~1api~1audit~1batch/post/responses/200`,
        access: "x402 v2 payment; no account or API key", billing_unit: "flat batch (up to 50 URLs); settles only when at least one audit succeeds", idempotency: "read-only audits; retry with a fresh payment per batch",
        side_effects: "read-only public fetches (concurrency-capped)", rate_limits: "max 50 URLs per batch, 8 concurrent fetches", error_model: "stable JSON code and message, per-URL error entries", data_retention: "no target credentials or cookies collected",
        limitations: ["single page per URL", "no JavaScript rendering", "max 50 URLs per batch", "flat price regardless of URL count"],
        documentation: `${PUBLIC_API_BASE_URL}/openapi.json`, support: "mailto:info@santosautomation.com",
        price: { amount: process.env.BATCH_AUDIT_PRICE_USDC ?? "0.50", currency: "USDC", protocol: "x402-v2", network: "eip155:8453" },
        examples: {
          request: `curl -X POST "${PUBLIC_API_BASE_URL}/api/audit/batch" -H "content-type: application/json" -H "PAYMENT-SIGNATURE: <x402 v2 signed payload>" -d '{"urls":["https://example.com","https://bad-host.invalid"]}'`,
          response: { results: [{ url: "https://example.com/", ok: true, report: { overall_score: 68, signature: "<hex>" } }, { url: "https://bad-host.invalid", ok: false, error: { message: "Target unreachable", code: "TARGET_UNREACHABLE" } }] },
        },
      },
      {
        id: "agent-readiness.quick", title: "Agent Readiness Audit", version: "1.0.0", description: "Select to assess public agent-facing discovery, APIs, MCP, trust, and resource-scoped machine-commerce pricing without active target actions.",
        endpoint: `${PUBLIC_API_BASE_URL}/api/agent-readiness?url={url}`, method: "GET", mode: "synchronous",
        expected_latency: "seconds", input_schema: { type: "object", required: ["url"], properties: { url: { type: "string", format: "uri" }, depth: { type: "string", enum: ["quick"] } } },
        output_schema: `${PUBLIC_API_BASE_URL}/openapi.json#/components/schemas/AgentReadinessResult`,
        access: "x402 v2 payment; no account or API key", billing_unit: AGENT_READINESS_BILLING_UNIT,
        idempotency: "safe read-only GET; payment settles only on a successful response", side_effects: "none on the target beyond bounded public reads", rate_limits: "maximum eight additional public requests",
        error_model: "stable JSON code and message", data_retention: "no authentication, payment signature, cookie, or secret collection",
        limitations: ["public surfaces only", "does not authenticate to or pay the audited target", "no MCP tools/call", "llms.txt proposal and optional preview-registry evidence"],
        documentation: `${PUBLIC_API_BASE_URL}/openapi.json`, support: "mailto:info@santosautomation.com",
        schema_version: "1.0.0", price: { amount: readinessPrice, currency: "USDC", protocol: "x402-v2", network: "eip155:8453" },
        examples: {
          request: `curl "${PUBLIC_API_BASE_URL}/api/agent-readiness?url=https://example.com&depth=quick" -H "PAYMENT-SIGNATURE: <x402 v2 signed payload>"`,
          response: { website_intelligence_score: 82, website_intelligence: { dimensions: { discoverable: 91, understandable: 78, callable: 73, trustworthy: 86 } }, grade: "B", readiness_level: "mostly-ready", findings: [{ id: "openapi-discovery", status: "pass" }], signature_alg: "HMAC-SHA256", signature: "<hex>" },
        },
      },
      {
        id: "web.safe-fetch", title: "Safe Fetch", version: "1.0.0", description: "Select to retrieve one public URL's raw text body through a hardened SSRF-guarded fetcher with redirects, headers, and timing metadata.",
        endpoint: `${PUBLIC_API_BASE_URL}/v1/fetch?url={url}`, method: "GET", mode: "synchronous",
        expected_latency: "seconds", input_schema: { type: "object", required: ["url"], properties: { url: { type: "string", format: "uri" } } },
        output_schema: `${PUBLIC_API_BASE_URL}/openapi.json#/paths/~1v1~1fetch/get/responses/200`,
        access: "x402 v2 payment; no account or API key", billing_unit: "successful fetch", idempotency: "read-only; payment settles only on a successful response",
        side_effects: "read-only public fetch", rate_limits: "bounded target fetch (15s, 2MB, ports 80/443)", error_model: "stable JSON code and message", data_retention: "fetched content is returned, not stored",
        limitations: ["single URL", "text formats only", "no crawling", "no JavaScript rendering"],
        documentation: `${PUBLIC_API_BASE_URL}/openapi.json`, support: "mailto:info@santosautomation.com",
        price: { amount: process.env.SAFE_FETCH_PRICE_USDC ?? "0.002", currency: "USDC", protocol: "x402-v2", network: "eip155:8453" },
        examples: {
          request: `curl "${PUBLIC_API_BASE_URL}/v1/fetch?url=https://example.com/data.json" -H "PAYMENT-SIGNATURE: <x402 v2 signed payload>"`,
          response: { url: "https://example.com/data.json", final_url: "https://example.com/data.json", http_status: 200, headers: { "content-type": "application/json" }, body: "{\"hello\":\"world\"}", body_bytes: 17 },
        },
      },
      {
        id: "content.extract-markdown", title: "Page-to-Markdown Extraction", version: "1.0.0", description: "Select to convert one public web page into clean Markdown with title, links, and metadata for RAG and research workflows.",
        endpoint: `${PUBLIC_API_BASE_URL}/v1/extract`, method: "POST", mode: "synchronous",
        expected_latency: "seconds", input_schema: { type: "object", required: ["url"], properties: { url: { type: "string", format: "uri" } } },
        output_schema: `${PUBLIC_API_BASE_URL}/openapi.json#/paths/~1v1~1extract/post/responses/200`,
        access: "x402 v2 payment; no account or API key", billing_unit: "successful extraction", idempotency: "read-only; payment settles only on a successful response",
        side_effects: "read-only public fetch", rate_limits: "bounded target fetch (15s, 5MB)", error_model: "stable JSON code and message", data_retention: "page content is returned, not stored",
        limitations: ["single page", "no crawling", "no JavaScript rendering"],
        documentation: `${PUBLIC_API_BASE_URL}/openapi.json`, support: "mailto:info@santosautomation.com",
        price: { amount: process.env.EXTRACT_PRICE_USDC ?? "0.005", currency: "USDC", protocol: "x402-v2", network: "eip155:8453" },
        examples: {
          request: `curl -X POST "${PUBLIC_API_BASE_URL}/v1/extract" -H "content-type: application/json" -H "PAYMENT-SIGNATURE: <x402 v2 signed payload>" -d '{"url":"https://example.com/article"}'`,
          response: { http_status: 200, title: "Example article", markdown: "# Example article\n\nBody text…", links: [{ url: "https://example.com/next", text: "Next page" }], word_count: 245 },
        },
      },
      {
        id: "content.extract-structured", title: "Structured Extraction", version: "1.0.0", description: "Select to extract structured JSON fields from one public web page against your own JSON Schema, using an LLM with forced tool-use and schema validation on the output.",
        endpoint: `${PUBLIC_API_BASE_URL}/v1/extract/structured`, method: "POST", mode: "synchronous",
        expected_latency: "seconds", input_schema: { type: "object", required: ["url", "schema"], properties: { url: { type: "string", format: "uri" }, schema: { type: "object", description: "Self-contained JSON Schema (type: object, no $ref) describing the fields to extract. Max 4000 characters." } } },
        output_schema: `${PUBLIC_API_BASE_URL}/openapi.json#/paths/~1v1~1extract~1structured/post/responses/200`,
        access: "x402 v2 payment; no account or API key", billing_unit: "successful extraction (output validated against caller schema)", idempotency: "read-only; payment settles only when the extracted data validates against the caller's schema",
        side_effects: "read-only public fetch plus one upstream LLM call", rate_limits: "bounded target fetch (15s, 5MB); page content truncated to 8000 characters before extraction; model output capped at 1024 tokens regardless of schema size", error_model: "stable JSON code and message", data_retention: "page content and extracted data are returned, not stored",
        limitations: ["single page", "no crawling", "no JavaScript rendering", "caller-supplied JSON Schema, self-contained only (no external $ref)", "very long pages are truncated before extraction"],
        documentation: `${PUBLIC_API_BASE_URL}/openapi.json`, support: "mailto:info@santosautomation.com",
        price: { amount: process.env.STRUCTURED_EXTRACT_PRICE_USDC ?? "0.08", currency: "USDC", protocol: "x402-v2", network: "eip155:8453" },
        examples: {
          request: `curl -X POST "${PUBLIC_API_BASE_URL}/v1/extract/structured" -H "content-type: application/json" -H "PAYMENT-SIGNATURE: <x402 v2 signed payload>" -d '{"url":"https://example.com/product","schema":{"type":"object","properties":{"price":{"type":"string"}},"required":["price"]}}'`,
          response: { data: { price: "$49.00" }, valid: true },
        },
      },
      {
        id: "render.screenshot", title: "Screenshot & PDF Render", version: "1.0.0", description: "Select to render one public page as a PNG, JPEG, or print-rendered A4 PDF in a real isolated Chromium browser — JavaScript executes, so SPAs and client-rendered content are captured as a real visitor sees them. Useful for deploy verification, visual monitoring, link previews, PDF archival, and vision-model input.",
        endpoint: `${PUBLIC_API_BASE_URL}/v1/screenshot?url={url}`, method: "GET", mode: "synchronous",
        expected_latency: "seconds (a cold worker wakes on demand; retry on 504)", input_schema: { type: "object", required: ["url"], properties: { url: { type: "string", format: "uri" }, format: { type: "string", enum: ["png", "jpeg", "pdf"] }, device: { type: "string", enum: ["desktop", "mobile"] }, full_page: { type: "boolean" } } },
        output_schema: `${PUBLIC_API_BASE_URL}/openapi.json#/paths/~1v1~1screenshot/get/responses/200`,
        access: "x402 v2 payment; no account or API key", billing_unit: "successful render", idempotency: "read-only; payment settles only when render bytes are returned",
        side_effects: "read-only public browser navigation", rate_limits: "bounded browser requests, bytes, and runtime", error_model: "stable JSON code and message on failures; binary on success", data_retention: "render artifacts expire within 72 hours",
        limitations: ["single page", "public pages only — no login-protected content", "fresh anonymous visitor: no cookies carried", "binary response"],
        documentation: `${PUBLIC_API_BASE_URL}/openapi.json`, support: "mailto:info@santosautomation.com",
        price: { amount: process.env.SCREENSHOT_PRICE_USDC ?? "0.01", currency: "USDC", protocol: "x402-v2", network: "eip155:8453" },
        examples: {
          request: `curl "${PUBLIC_API_BASE_URL}/v1/screenshot?url=https://example.com&format=png&device=mobile&full_page=true" -H "PAYMENT-SIGNATURE: <x402 v2 signed payload>" -o page.png`,
          response: "Binary image/png (or image/jpeg, application/pdf) response body; JSON error model on failure.",
        },
      },
      {
        id: "site-audit.deep-page", title: "Deep Website Intelligence Audit", version: "3.0.0", description: "Select for browser-rendered website intelligence evidence and optional Agent Readiness discovery.",
        endpoint: `${PUBLIC_API_BASE_URL}/v1/audits`, method: "POST", mode: "asynchronous",
        expected_latency: "tens of seconds to minutes", input_schema: `${PUBLIC_API_BASE_URL}/openapi.json#/paths/~1v1~1audits/post/requestBody`, output_schema: `${PUBLIC_API_BASE_URL}/openapi.json#/paths/~1v1~1audits~1{job_id}~1report/get/responses/200`,
        access: "x402 v2 payment plus per-job bearer access token", billing_unit: "bounded compute reservation", idempotency: "Idempotency-Key supported",
        side_effects: "read-only public browser navigation", rate_limits: "bounded browser requests, bytes, runtime, and artifacts", error_model: "versioned job and report errors",
        data_retention: "short-lived report artifacts; target cookie values are never captured", limitations: ["single page", "lab data", "no authenticated flows or penetration testing"],
        documentation: `${PUBLIC_API_BASE_URL}/openapi.json`, support: "mailto:info@santosautomation.com",
        price: { amount: process.env.DEEP_AUDIT_PRICE_USDC ?? "0.225", currency: "USDC", protocol: "x402-v2", network: "eip155:8453" },
        examples: {
          request: `curl -X POST "${PUBLIC_API_BASE_URL}/v1/audits" -H "content-type: application/json" -H "Idempotency-Key: <uuid>" -H "PAYMENT-SIGNATURE: <x402 v2 signed payload>" -d '{"url":"https://example.com"}'`,
          response: { job_id: "job_01J…", status: "queued", access_token: "<per-job bearer>", poll: `${PUBLIC_API_BASE_URL}/v1/audits/job_01J…/events`, report: `${PUBLIC_API_BASE_URL}/v1/audits/job_01J…/report` },
        },
      },
      {
        id: "site.badge", title: "Agent-Ready Badge (SVG)", version: "1.0.0", description: "Select to embed a live SVG shield showing a site's latest public Agent Readiness score and verification date.",
        endpoint: `${PUBLIC_API_BASE_URL}/v1/badge?url={url}`, method: "GET", mode: "synchronous",
        expected_latency: "seconds", input_schema: { type: "object", required: ["url"], properties: { url: { type: "string", format: "uri" } } },
        output_schema: `${PUBLIC_API_BASE_URL}/openapi.json#/paths/~1v1~1badge/get/responses/200`,
        access: "free; no account, no payment, no quota (public image)", billing_unit: "none — free", idempotency: "safe read-only GET",
        side_effects: "none", rate_limits: "none; cacheable image (Cache-Control: public, max-age=3600)", error_model: "gray 'unverified' badge when no public report exists", data_retention: "reads the site's latest public report only",
        limitations: ["reflects the latest public report for the domain", "shows a re-verify state when the report is over 30 days old"],
        documentation: `${PUBLIC_API_BASE_URL}/openapi.json`, support: "mailto:info@santosautomation.com",
        price: { amount: "0", currency: "USDC" },
        examples: {
          request: `[![Agent-Ready badge](${PUBLIC_API_BASE_URL}/v1/badge?url=example.com)](https://www.santosautomation.com/reports/example.com)`,
          response: "image/svg+xml — gold shield with score and verification date; muted 're-verify' state after 30 days; gray 'unverified' when the domain has no public report.",
        },
      },
      {
        id: "report.verify", title: "Report Signature Verification", version: "1.0.0", description: "Select to verify the HMAC-SHA256 signature on a Santos audit report and confirm it was issued unmodified.",
        endpoint: `${PUBLIC_API_BASE_URL}/v1/verify`, method: "POST", mode: "synchronous",
        expected_latency: "instant", input_schema: { type: "object", description: "The full report JSON as returned by any audit endpoint, including its signature fields." },
        output_schema: `${PUBLIC_API_BASE_URL}/openapi.json#/paths/~1v1~1verify/post/responses/200`,
        access: "free; no account, no payment", billing_unit: "none — free", idempotency: "read-only verification",
        side_effects: "none", rate_limits: "30 verifications per hour per IP", error_model: "stable JSON code and message", data_retention: "submitted reports are verified in memory, not stored",
        limitations: ["HMAC-SHA256 signature scheme only", "unsigned or modified reports return valid: false"],
        documentation: `${PUBLIC_API_BASE_URL}/openapi.json`, support: "mailto:info@santosautomation.com",
        price: { amount: "0", currency: "USDC" },
        examples: {
          request: `curl -X POST "${PUBLIC_API_BASE_URL}/v1/verify" -H "content-type: application/json" --data @report.json`,
          response: { valid: true, url: "https://example.com/", score: 82, signed_at: "2026-07-23T12:00:00.000Z" },
        },
      },
      {
        id: "content.llms-txt-demo", title: "llms.txt Generator (verified-email free tier)", version: "1.0.0", description: "Select to draft a standards-shaped llms.txt for a public website from a one-page sample (title, description, heading outline, internal links).",
        endpoint: `${PUBLIC_API_BASE_URL}/v1/llms-txt/demo?url={url}&token={token}`, method: "GET", mode: "synchronous",
        expected_latency: "seconds", input_schema: { type: "object", required: ["url", "token"], properties: { url: { type: "string", format: "uri" }, token: { type: "string", description: "Verified-email token from POST /api/leads/verify/request → /api/leads/verify/confirm (valid 30 days)." } } },
        output_schema: `${PUBLIC_API_BASE_URL}/openapi.json#/paths/~1v1~1llms-txt~1demo/get/responses/200`,
        access: "free with a verified-email token; no payment", billing_unit: "none — free", idempotency: "safe read-only GET",
        side_effects: "read-only public fetch", rate_limits: "1 call/day per verified email, shared across the verified free tools (widget audit + llms.txt generator)", error_model: "stable JSON code and message", data_retention: "sampled content is returned, not stored",
        limitations: ["draft output — review before publishing", "1 page sampled", "no JavaScript rendering"],
        documentation: `${PUBLIC_API_BASE_URL}/openapi.json`, support: "mailto:info@santosautomation.com",
        price: { amount: "0", currency: "USDC" },
        examples: {
          request: `curl "${PUBLIC_API_BASE_URL}/v1/llms-txt/demo?url=https://example.com&token=<verified-email token>"`,
          response: { tier: "free-verified", url: "https://example.com/", llms_txt: "# Example\n\n> Example domain…\n\n## Pages\n\n- [Docs](https://example.com/docs)", notes: ["Draft — review before publishing", "1 page sampled"] },
        },
      },
    ],
  };
}
